config/routes.rb
Rails.application.routes.draw do
  devise_for :users,controllers: { sessions: 'devise/sessions' }
  root to: 'welcome#index'
  resources :charges, only: [:new, :create]
  resources :wikis do
    resources :collaborators, except: [:index]
  end

end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
  belongs_to :wiki
  belongs_to :user

   validates_uniqueness_of :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :wikis
  before_save { self.role ||= :standard }
  enum role: [:standard, :premium, :admin]

end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user
  has_many :collaborators
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include Pundit
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

 private

 def user_not_authorized
   flash[:alert] = "You are not authorized to perform this action."
   redirect_to(request.referrer || root_path)
 end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
    @stripe_btn_data = {
     key: "pk_test_wcoroil6VM5iYyHqvNjYDnmO",
     description: "Premium Membership for #{current_user.email}",
     amount: 1500
   }
  end
  def create
   # Creates a Stripe Customer object, for associating
   # with the charge
   if current_user.standard?
   Stripe.api_key = "sk_test_m9WsriA1M8abSwus9KvF4M8U"
   customer = Stripe::Customer.create(
     email: current_user.email,
     card: params[:stripeToken]
   )

   # Where the real magic happens
   charge = Stripe::Charge.create(
     customer: customer.id, # Note -- this is NOT the user_id in your app
     amount: 1500,
     description: "Premium Membership for - #{current_user.email}",
     currency: 'usd'
   )
   current_user.update_attribute(:role, 'premium')
   flash[:notice] = "Your membership is now premium, #{current_user.email}!"
   redirect_to root_path # or wherever

   # Stripe will send back CardErrors, with friendly messages
   # when something goes wrong.
   # This `rescue block` catches and displays those errors.
 else
   current_user.update_attribute(:role, 'standard')
 end
   rescue Stripe::CardError => e
     flash[:alert] = e.message
     redirect_to new_charge_path
 end
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
  def new
  @wiki = Wiki.find(params[:wiki_id])
  @collaborator = Collaborator.new
  end

  def create
  @collaborator = Collaborator.new
  @collaborator.user_id = params[:collaborator][:user]
  @wiki = Wiki.find(params[:wiki_id])
  @collaborator.wiki = @wiki
  @users = User.all

    if @collaborator.save
      flash[:notice] = "Wiki was saved."
      redirect_to @wiki
    else
      # if no successful alert the user and render the new view again.
      flash.now[:alert] = "There was an error saving the wiki. Please try again"
      render :new
  end
  end

  def edit
    @wiki = Wiki.find(params[:id])
  end

  def destroy
    @wiki = Wiki.find(params[:wiki_id])
     @collaborator = Collaborator.find(params[:id])
     if @collaborator.destroy
       flash[:notice] = "Deleted successfully."
       redirect_to @wiki
     else
       flash.now[:alert] = "There was an error deleting the user."
       render :show
     end
   end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user
      create_session(user)
      flash[:notice] = "Welcome, #{user.email}!"
      redirect_to root_path
    else
      flash.now[:alert] = 'Invalid email/password combination'
      render :new
    end
  end

  def destroy
    destroy_session(current_user)
    flash[:notice] = "You've been signed out, come back soon!"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class Users::SessionsController < Devise::SessionsController
  def new
    @user = User.new
  end
  def create
    @user = User.new
    @user.email = params[:user][:email]
    @user.password = params[:user][:password]
    @user.password_confirmation = params[:user][:password_confirmation]

    if @user.save
      flash[:notice] = "Welcome to Bloccit #{@user.email}!"
      create_session(@user)
      redirect_to root_path
    else
      flash.now[:alert] = "There was an error creating your account. Please try again."
      render :new
    end
  end

  def destroy
    destroy_session(current_user)
    flash[:notice] = "You've been signed out, come back soon!"
    redirect_to root_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController

  def index
    @wikis = Wiki.all
  end
  def new
    @wiki = Wiki.new
  end
  def create
  @wiki = Wiki.new
  @wiki.title = params[:wiki][:title]
  @wiki.body = markdown_content(params[:wiki][:body])
  @wiki.private = params[:wiki][:private]
  @wiki.user = current_user

    if @wiki.save
      flash[:notice] = "Wiki was saved."
      redirect_to @wiki
    else
      # if no successful alert the user and render the new view again.
      flash.now[:alert] = "There was an error saving the wiki. Please try again"
      render :new
    end
  end
  def edit
    @wiki = Wiki.find(params[:id])
  end
  def update
    @wiki = Wiki.find(params[:id])
    authorize @wiki
    if @wiki.update_attributes( wiki_params )
      @wiki.title = markdown_content(@wiki.title)
      @wiki.body = markdown_content(@wiki.body)
      flash[:notice] = "Wiki was updated."
      redirect_to  @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again"
      render :edit
    end
  end

  def show
    @wiki = Wiki.find(params[:id])
  end

  def destroy
     @wiki = Wiki.find(params[:id])
     authorize @wiki
     if @wiki.destroy
       flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
       redirect_to wikis_path
     else
       flash.now[:alert] = "There was an error deleting the wiki."
       render :show
     end
   end



  private
    def wiki_params
      params.require(:wiki).permit( :title, :body, :private )
    end


  def markdown_content(body)
     markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML)
    markdown.render(body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
  def is_collaborator?(wiki)
    wiki.collaborators.where(user_id: current_user)
  end
end

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
   <h4>Membership for <%= current_user.email %></h4>
   <p> Change membership to: </p>
   <% if current_user.role = "standard"  %>
    Premium?
  <% else %>
    Back to Basic?
   <% end %>
   <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount="<%= @stripe_btn_data[:amount] %>" data-description="<%= @stripe_btn_data[:description] %>" ></script>
 <% end %>

app/views/collaborators/new.html.erb
<%= form_for [@wiki, @collaborator] do |f| %>
  <%= f.label :user %>
  <%= f.collection_select :user, User.all, :id, :email, class: 'form-control' %>
  <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-success' %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocipedia</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav>
      <% if current_user %>
      Welcome <%= current_user.email  %> - <%= current_user.role %> member !
      <%= link_to "Change Membership", new_charge_path %>
      <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
      <% else %>
      <%= link_to "Sign In", new_user_session_path %>
       <%= link_to "Sign Up", new_user_registration_path %>
       <%= current_user %>
       <% end %>
       <%= link_to "Wikis", wikis_path %>
</nav>
<% if flash[:notice] %>
     <div class="alert alert-success">
       <button type="button" class="close" data-dismiss="alert">&times;</button>
       <%= flash[:notice] %>
     </div>
   <% elsif flash[:alert] %>
     <div class="alert alert-warning">
       <button type="button" class="close" data-dismiss="alert">&times;</button>
       <%= flash[:alert] %>
     </div>
   <% end %>
<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1> Blocipedia </h1>

app/views/wikis/edit.html.erb
<%= form_for @wiki do |f| %>
   <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', placeholder: "Enter post title" %>
   <%= f.label :body %>
   <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter post body" %>
   <%= f.label :private %>
   <%= f.check_box :private, rows: 8, class: 'form-control' %>
 <div class="form-group">
   <%= f.submit "Save", class: 'btn btn-success' %>
 </div>
<% end %>

app/views/wikis/index.html.erb
<h1> Wikis </h1><%= link_to "New Wiki", new_wiki_path %>
<% @wikis.each do |wiki | %>
<% if wiki.private %>
<% if current_user.admin? || current_user.premium? || is_collaborator?(wiki)%>
<h3> * Private Post * <%= link_to wiki.title, wiki_path(wiki.id) %> by<small><%= wiki.user.email %></small></h3>
<hr/>
<% end %>
<% else %>
<h3><%= link_to wiki.title, wiki_path(wiki.id) %> by<small><%= wiki.user.email %></small></h3>
<hr/>
<% end %>

<% end %>

app/views/wikis/new.html.erb
<%= form_for @wiki do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, class: 'form-control', placeholder: "Enter post title" %>
  <%= f.label :body %>
  <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter post body" %>
  <% if current_user.admin? || current_user.premium? %>
  <%= f.label :private %>
  <%= f.check_box :private, rows: 8, class: 'form-control' %>
  <% end %>
  <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-success' %>
  </div>
<% end %>

app/views/wikis/show.html.erb
<h1> <%= @wiki.title %> by <%= @wiki.user.email %> </h1>
<% if current_user == @wiki.user || current_user.premium? || current_user.admin? || is_collaborator?(@wiki)%>
<%= link_to "Edit", edit_wiki_path(@wiki) %>
<%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this post?'} %>
<p> <%= @wiki.body.html_safe %> </p>
<% if current_user.premium? || current_user.admin?  && @wiki.private?  %>
  <h3> Collaborators </h3>
   <%= link_to "New Collaborator", new_wiki_collaborator_path(@wiki) %>
  <% @wiki.collaborators.each do |c| %>
  <p><%= c.user.email %><%= link_to "Delete", [@wiki, c], method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this collaborator?' } %></p>
  <% end %>
<% end %>
<% end %>